import { Jost } from "next/font/google";
import "./globals.css";

const fontJost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fontJost.variable}>
    <body className="antialiased font-sans">
      {children}
    </body>
  </html>
  );
}
